<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>MelodyMatch</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MelodyMatch.Domain\MelodyMatch.Domain.csproj" />
    <ProjectReference Include="..\MelodyMatch.TestBase\MelodyMatch.TestBase.csproj" />
  </ItemGroup>

</Project>
